#!/bin/bash
echo "================================================================"
echo "CKA Q19: DATA PLANE & NETWORK TRIAGE"
echo "================================================================"
echo "Symptom 1: A worker node is showing 'NotReady'."
echo "Symptom 2: New pods are stuck in 'ContainerCreating'."
echo "Symptom 3: Internal DNS resolution is failing."
echo "Symptom 4: A service exists but has no active endpoints."
echo ""
echo "TASK:"
echo "1. Restore the worker node to 'Ready' status."
echo "2. Ensure the CNI is properly configured on the worker."
echo "3. Fix the CoreDNS deployment."
echo "4. Correct the service 'troubleshooting-svc' to route traffic."
echo "================================================================"
